### ISSUE TITLE
Wrong times at stop #2249

### ISSUE THREAD

**Issue by wyszynskif** [Hillsborough-Transit-Authority/hart-data#2]
Customer submitted. MacDill @ Paul Ave. @barbeau @haneys 

![bz9ypisiuaaocok png large](https://f.cloud.github.com/assets/5666420/1622461/da9135f0-56a5-11e3-89b0-afabcb3fa48c.png)

**Comment by barbeau** [comment]
@haneys Is "5:45am, 6:10am, 6:47am, 7:16am, 7:47am, 8:11am" the correct schedule for the stop "Macdill Av @ Paul Av" for Route 4?

**Comment by barbeau** [comment]
Looks like something is still wrong for this stop - I believe there should be an arrival at 4:14pm arrival of Route 73 from the GTFS data, but I'm not seeing any arrivals in OBA:
http://tampa.onebusaway.org/where/standard/stop.action?id=Hillsborough%20Area%20Regional%20Transit_2249

cc @StPierreP

**Comment by StPierreP** [comment]
@barbeau @haneys I do not have stop 2249 assigned to the route 4 anymore. I am looking through emails. We do not have a route 73. Does this possibly need to be removed from the GTFS feed.

**Comment by StPierreP** [comment]
@barbeau @haneys Currently, the stop is not in Trapeze and should have been removed from OBA. therefore, that is why it is not showing having a schedule.Will work with our bus stops folks and find out if we are putting the stop back in or not.

**Comment by barbeau** [comment]
@StPierreP Looks like new HART GTFS data was just posted today (I know Tim W. was working on this) at http://www.gohart.org/google/google_transit.zip.  Looking in stops.txt, stop 2249 does not appear in that data.  So, it looks like the GTFS data is now correct.  It's just a matter of @sheldonabrown updating the OBA production servers with the new GTFS data (which I'm sure he's working on right now ;) ).  So, I'm going to close this issue since it appears the data is correct (which is what this issue tracker is focused on).  However, it would be good for someone to double-check that this is fixed in OBA when OBA goes live with the new GTFS data.
